version: '3.7'
services:
  parking:
    container_name: parking
    build: .
    image: parking:latest
    ports:
      - 8080:8080
    networks:
      - parking-network
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - parking-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=parking
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - parking-network
volumes:
  mysql-data:
networks:
  parking-network:
    driver: bridge
